backend:
  name: github
  repo: ysdn2018/the-next-base

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
