backend:
  name: github
  repo: ysdn2018/the-next-base

media_folder: src/content/assets
public_folder: static/assets

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: post}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown}
